on:
  repository_dispatch:
    types: [add-pgp-key]

jobs:
  extract-and-save:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Decode, extract email manually, save key
        run: |
          echo "Start decoding key_data"

          # Step 1: Decode the URL-encoded comment body
          echo "${{ github.event.client_payload.key_data }}" | \
            sed 's/+/ /g' | \
            python3 -c "import sys, urllib.parse; print(urllib.parse.unquote(sys.stdin.read()))" > key.asc

          echo "Decoded Key Content:"
          cat key.asc

          echo "Extracting email from [email] line..."

          # Step 2: Extract email address from '[email] email@domain.com'
          EMAIL=$(grep -i '^\[email\]' key.asc | awk '{print $2}' | head -n1)

          if [ -z "$EMAIL" ]; then
            echo "❌ No email line found in comment! Please add '[email] your@email.com' before the PGP key."
            exit 1
          fi

          echo "✅ Extracted email: $EMAIL"

          # Step 3: Save key (excluding the [email] line)
          mkdir -p pgp_keys
          
          # Save only the PGP key block, skip [email] line
          awk 'BEGIN{found=0} /^-----BEGIN PGP PUBLIC KEY BLOCK-----/{found=1} found' key.asc > "pgp_keys/${EMAIL}.asc"

          echo "EMAIL=$EMAIL" >> $GITHUB_ENV

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add pgp_keys/
          git commit -m "Add PGP key for $EMAIL"
          git push
