on:
  repository_dispatch:
    types: [add-pgp-key]

jobs:
  extract-and-save:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Decode and extract email
        run: |
          echo "${{ github.event.client_payload.key_data }}" | python3 -c "import sys, urllib.parse; print(urllib.parse.unquote(sys.stdin.read()))" > key.asc

          # Clean up and extract email
          EMAIL=$(grep -a -oP '<\K[^>]+(?=>)' key.asc | head -n1)

          if [ -z "$EMAIL" ]; then
            echo "No email found in key!"
            exit 1
          fi

          echo "Extracted email: $EMAIL"

          # Save the key using email as filename
          mkdir -p pgp_keys
          cp key.asc "pgp_keys/$EMAIL.asc"

          # Save email variable for next step
          echo "EMAIL=$EMAIL" >> $GITHUB_ENV

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add pgp_keys/
          git commit -m "Add PGP key for $EMAIL"
          git push
